export const skills = [
    { value: "java", label: "Java" },
    { value: "springBoot", label: "Spring Boot" },
    { value: "hibernate", label: "Hibernate" },
    { value: "mysql", label: "MySQL" },
    { value: "oracle", label: "Oracle" },
    { value: "html", label: "HTML" },
    { value: "css", label: "CSS" },
    { value: "javascript", label: "JavaScript" },
    { value: "typescript", label: "TypeScript" },
    { value: "react", label: "React" },
    { value: "redux", label: "Redux" },
    { value: "nodejs", label: "Node.js" },
    { value: "express", label: "Express" },
    { value: "angular", label: "Angular" },
    { value: "mongodb", label: "MongoDB" },
    { value: "git", label: "Git" },
    { value: "github", label: "GitHub" },
    { value: "docker", label: "Docker" },
    { value: "kubernetes", label: "Kubernetes" },
    { value: "aws", label: "AWS" },
    { value: "azure", label: "Azure" },
    { value: "linux", label: "Linux" },
    { value: "graphql", label: "GraphQL" },
    { value: "restapi", label: "REST API" },
    { value: "json", label: "JSON" },
    { value: "figma", label: "Figma" },
    { value: "sass", label: "SASS" },
    { value: "bootstrap", label: "Bootstrap" },
    { value: "mui", label: "MUI" },
    { value: "jest", label: "Jest" },
    { value: "junit", label: "JUnit" },
    { value: "postman", label: "Postman" },
    { value: "cucumber", label: "Cucumber" },
    { value: "ci_cd", label: "CI/CD" },
    { value: "jenkins", label: "Jenkins" },
    { value: "swagger", label: "Swagger" },
    { value: "microservices", label: "Microservices" },
    { value: "websockets", label: "WebSockets" }
  ]