export const qualifications = [
    { label: "10th Pass", value: "10th Pass" },
    { label: "12th Pass", value: "12th Pass" },
    { label: "Acting Diploma", value: "Acting Diploma" },
    { label: "Adobe Certified Expert", value: "Adobe Certified Expert" },
    { label: "ANM (Auxiliary Nurse Midwife)", value: "ANM (Auxiliary Nurse Midwife)" },
    { label: "Autodesk Certified Professional", value: "Autodesk Certified Professional" },
    { label: "Aviation Certification", value: "Aviation Certification" },
    { label: "AWS Certified Solutions Architect", value: "AWS Certified Solutions Architect" },
    { label: "BA", value: "BA" },
    { label: "BAMS", value: "BAMS" },
    { label: "BCA", value: "BCA" },
    { label: "B.Arch", value: "B.Arch" },
    { label: "BBA", value: "BBA" },
    { label: "B.Com", value: "B.Com" },
    { label: "BDS", value: "BDS" },
    { label: "B.E / B.Tech", value: "B.E / B.Tech" },
    { label: "B.Ed", value: "B.Ed" },
    { label: "BFA", value: "BFA" },
    { label: "BHM", value: "BHM" },
    { label: "BHMS", value: "BHMS" },
    { label: "B.Pharm", value: "B.Pharm" },
    { label: "BPT", value: "BPT" },
    { label: "B.Sc", value: "B.Sc" },
    { label: "BSW", value: "BSW" },
    { label: "BUMS", value: "BUMS" },
    { label: "BVSc", value: "BVSc" },
    { label: "CCNA (Cisco Certified Network Associate)", value: "CCNA (Cisco Certified Network Associate)" },
    { label: "CCNP (Cisco Certified Network Professional)", value: "CCNP (Cisco Certified Network Professional)" },
    { label: "CEH (Certified Ethical Hacker)", value: "CEH (Certified Ethical Hacker)" },
    { label: "CFA (Chartered Financial Analyst)", value: "CFA (Chartered Financial Analyst)" },
    { label: "Certified Data Professional (CDP)", value: "Certified Data Professional (CDP)" },
    { label: "Certified Financial Planner (CFP)", value: "Certified Financial Planner (CFP)" },
    { label: "Certified Kubernetes Administrator (CKA)", value: "Certified Kubernetes Administrator (CKA)" },
    { label: "Certified Nutrition Specialist", value: "Certified Nutrition Specialist" },
    { label: "Certified Personal Trainer", value: "Certified Personal Trainer" },
    { label: "Certified Public Accountant (CPA)", value: "Certified Public Accountant (CPA)" },
    { label: "Certified Scrum Master (CSM)", value: "Certified Scrum Master (CSM)" },
    { label: "Certified Yoga Instructor", value: "Certified Yoga Instructor" },
    { label: "CFA (Chartered Financial Analyst)", value: "CFA (Chartered Financial Analyst)" },
    { label: "Chartered Accountant (CA)", value: "Chartered Accountant (CA)" },
    { label: "CISSP (Certified Information Systems Security Professional)", value: "CISSP (Certified Information Systems Security Professional)" },
    { label: "Company Secretary (CS)", value: "Company Secretary (CS)" },
    { label: "CompTIA A+", value: "CompTIA A+" },
    { label: "CompTIA Security+", value: "CompTIA Security+" },
    { label: "Culinary Arts Diploma", value: "Culinary Arts Diploma" },
    { label: "Data Science Specialization", value: "Data Science Specialization" },
    { label: "Digital Marketing Certification", value: "Digital Marketing Certification" },
    { label: "Diploma", value: "Diploma" },
    { label: "Docker Certified Associate", value: "Docker Certified Associate" },
    { label: "Event Management Certification", value: "Event Management Certification" },
    { label: "Fashion Design Diploma", value: "Fashion Design Diploma" },
    { label: "Film Making Certification", value: "Film Making Certification" },
    { label: "Foreign Language Diploma", value: "Foreign Language Diploma" },
    { label: "FRM (Financial Risk Manager)", value: "FRM (Financial Risk Manager)" },
    { label: "GNM (General Nursing and Midwifery)", value: "GNM (General Nursing and Midwifery)" },
    { label: "Google Analytics Certification", value: "Google Analytics Certification" },
    { label: "Google Cloud Certified", value: "Google Cloud Certified" },
    { label: "Graphic Design Certification", value: "Graphic Design Certification" },
    { label: "Hotel Management Certification", value: "Hotel Management Certification" },
    { label: "ICWA", value: "ICWA" },
    { label: "Interior Design Diploma", value: "Interior Design Diploma" },
    { label: "ISTQB Certified Tester", value: "ISTQB Certified Tester" },
    { label: "Journalism and Mass Communication Diploma", value: "Journalism and Mass Communication Diploma" },
    { label: "LLB", value: "LLB" },
    { label: "LLM", value: "LLM" },
    { label: "MA", value: "MA" },
    { label: "MBA", value: "MBA" },
    { label: "MBBS", value: "MBBS" },
    { label: "MCA", value: "MCA" },
    { label: "M.Com", value: "M.Com" },
    { label: "M.E / M.Tech", value: "M.E / M.Tech" },
    { label: "M.Ed", value: "M.Ed" },
    { label: "MFA", value: "MFA" },
    { label: "MHM", value: "MHM" },
    { label: "Microsoft Certified: Azure Fundamentals", value: "Microsoft Certified: Azure Fundamentals" },
    { label: "MPT", value: "MPT" },
    { label: "M.Sc", value: "M.Sc" },
    { label: "MSW", value: "MSW" },
    { label: "Music Certification", value: "Music Certification" },
    { label: "MVSc", value: "MVSc" },
    { label: "Nursing Diploma", value: "Nursing Diploma" },
    { label: "Oracle Certified Java Programmer", value: "Oracle Certified Java Programmer" },
    { label: "Ph.D", value: "Ph.D" },
    { label: "PMP (Project Management Professional)", value: "PMP (Project Management Professional)" },
    { label: "PRINCE2 Certification", value: "PRINCE2 Certification" },
    { label: "RHCE (Red Hat Certified Engineer)", value: "RHCE (Red Hat Certified Engineer)" },
    { label: "Salesforce Certification", value: "Salesforce Certification" },
    { label: "Six Sigma Certification", value: "Six Sigma Certification" },
    { label: "TOGAF Certification", value: "TOGAF Certification" }
];