export const skills = [
  // Stack-based skills
  { value: "fullStackJava", label: "Full Stack Java" },
  { value: "mernStack", label: "MERN Stack" },
  { value: "meanStack", label: "MEAN Stack" },
  { value: "lamp", label: "LAMP Stack" },
  { value: "jamstack", label: "JAMstack" },
  { value: "dotnet", label: ".NET Stack" },
  { value: "python", label: "Python Stack" },
  { value: "ruby", label: "Ruby on Rails" },

  // Role-based skills
  { value: "frontend", label: "Frontend" },
  { value: "backend", label: "Backend" },
  { value: "devops", label: "DevOps" },
  { value: "devSecOps", label: "DevSecOps" },
  { value: "sre", label: "SRE (Site Reliability Engineering)" },
  { value: "cloud", label: "Cloud" },
  { value: "testing", label: "Testing" },
  { value: "qaautomation", label: "QA Automation" },
  { value: "design", label: "UI/UX Design" },
  
  // Technology areas
  { value: "tooling", label: "Tooling" },
  { value: "api", label: "API" },
  { value: "monitoring", label: "Monitoring" },
  { value: "gamedev", label: "Game Development" },
  { value: "ai", label: "AI/ML" },
  { value: "mobile", label: "Mobile Development" },
  { value: "datascience", label: "Data Science" },
  { value: "blockchain", label: "Blockchain" },
  { value: "cybersecurity", label: "Cybersecurity" },
  { value: "embedded", label: "Embedded Systems" },
  { value: "iot", label: "IoT Development" },
  { value: "serverless", label: "Serverless" },
  { value: "dataengineering", label: "Data Engineering" },
  { value: "ar", label: "AR/VR Development" },
  { value: "lowcode", label: "Low-Code/No-Code" },
  { value: "microservices", label: "Microservices" },
  { value: "bigdata", label: "Big Data" },

  // Programming Languages
  { value: "javascript", label: "JavaScript" },
  { value: "typescript", label: "TypeScript" },
  { value: "python", label: "Python" },
  { value: "java", label: "Java" },
  { value: "csharp", label: "C#" },
  { value: "php", label: "PHP" },
  { value: "ruby", label: "Ruby" },
  { value: "go", label: "Go" },
  { value: "rust", label: "Rust" },
  { value: "swift", label: "Swift" },
  { value: "kotlin", label: "Kotlin" },
  { value: "scala", label: "Scala" },
  { value: "dart", label: "Dart" },
  { value: "r", label: "R" },
  { value: "cpp", label: "C++" },
  { value: "c", label: "C" },

  // Frontend Technologies
  { value: "react", label: "React" },
  { value: "angular", label: "Angular" },
  { value: "vue", label: "Vue.js" },
  { value: "svelte", label: "Svelte" },
  { value: "nextjs", label: "Next.js" },
  { value: "nuxtjs", label: "Nuxt.js" },
  { value: "gatsby", label: "Gatsby" },
  { value: "html", label: "HTML" },
  { value: "css", label: "CSS" },
  { value: "sass", label: "Sass" },
  { value: "less", label: "Less" },
  { value: "tailwind", label: "Tailwind CSS" },
  { value: "bootstrap", label: "Bootstrap" },
  { value: "jquery", label: "jQuery" },
  { value: "webcomponents", label: "Web Components" },
  { value: "redux", label: "Redux" },
  { value: "graphql", label: "GraphQL" },
  { value: "apollo", label: "Apollo" },

  // Backend Technologies
  { value: "nodejs", label: "Node.js" },
  { value: "express", label: "Express.js" },
  { value: "nestjs", label: "NestJS" },
  { value: "spring", label: "Spring Framework" },
  { value: "django", label: "Django" },
  { value: "flask", label: "Flask" },
  { value: "laravel", label: "Laravel" },
  { value: "rails", label: "Ruby on Rails" },
  { value: "aspnet", label: "ASP.NET" },
  { value: "fastapi", label: "FastAPI" },

  // Databases
  { value: "mysql", label: "MySQL" },
  { value: "postgresql", label: "PostgreSQL" },
  { value: "mongodb", label: "MongoDB" },
  { value: "redis", label: "Redis" },
  { value: "oracle", label: "Oracle" },
  { value: "sqlserver", label: "SQL Server" },
  { value: "sqlite", label: "SQLite" },
  { value: "firebase", label: "Firebase" },
  { value: "dynamodb", label: "DynamoDB" },
  { value: "cassandra", label: "Cassandra" },
  { value: "elasticsearch", label: "Elasticsearch" },
  { value: "neo4j", label: "Neo4j" },

  // DevOps & Cloud
  { value: "docker", label: "Docker" },
  { value: "kubernetes", label: "Kubernetes" },
  { value: "aws", label: "AWS" },
  { value: "azure", label: "Azure" },
  { value: "gcp", label: "Google Cloud" },
  { value: "terraform", label: "Terraform" },
  { value: "ansible", label: "Ansible" },
  { value: "jenkins", label: "Jenkins" },
  { value: "githubactions", label: "GitHub Actions" },
  { value: "gitlabci", label: "GitLab CI/CD" },
  { value: "prometheus", label: "Prometheus" },
  { value: "grafana", label: "Grafana" },
  { value: "nginx", label: "NGINX" },
  { value: "apache", label: "Apache" },

  // Mobile Development
  { value: "reactnative", label: "React Native" },
  { value: "flutter", label: "Flutter" },
  { value: "android", label: "Android" },
  { value: "ios", label: "iOS" },
  { value: "xamarin", label: "Xamarin" },

  // Testing
  { value: "jest", label: "Jest" },
  { value: "mocha", label: "Mocha" },
  { value: "cypress", label: "Cypress" },
  { value: "selenium", label: "Selenium" },
  { value: "junit", label: "JUnit" },
  { value: "pytest", label: "PyTest" },
  { value: "testng", label: "TestNG" },

  // Other Tools
  { value: "git", label: "Git" },
  { value: "webpack", label: "Webpack" },
  { value: "babel", label: "Babel" },
  { value: "vite", label: "Vite" },
  { value: "eslint", label: "ESLint" },
  { value: "prettier", label: "Prettier" },
  { value: "figma", label: "Figma" },
  { value: "sketch", label: "Sketch" },
  { value: "xd", label: "Adobe XD" },
  { value: "blender", label: "Blender" },
  { value: "unity", label: "Unity" },
  { value: "unreal", label: "Unreal Engine" },
  { value: "solidity", label: "Solidity" }
];