export const skills = [
  { value: "java", label: "Java" },
  { value: "springBoot", label: "Spring Boot" },
  { value: "hibernate", label: "Hibernate" },
  { value: "mysql", label: "MySQL" },
  { value: "oracle", label: "Oracle" },
  { value: "html", label: "HTML" },
  { value: "css", label: "CSS" },
  { value: "javascript", label: "JavaScript" },
  { value: "typescript", label: "TypeScript" },
  { value: "react", label: "React" },
  { value: "redux", label: "Redux" },
  { value: "nodejs", label: "Node.js" },
  { value: "express", label: "Express" },
  { value: "angular", label: "Angular" },
  { value: "mongodb", label: "MongoDB" },
  { value: "git", label: "Git" },
  { value: "github", label: "GitHub" },
  { value: "docker", label: "Docker" },
  { value: "kubernetes", label: "Kubernetes" },
  { value: "aws", label: "AWS" },
  { value: "azure", label: "Azure" },
  { value: "linux", label: "Linux" },
  { value: "graphql", label: "GraphQL" },
  { value: "restapi", label: "REST API" },
  { value: "json", label: "JSON" },
  { value: "figma", label: "Figma" },
  { value: "sass", label: "SASS" },
  { value: "bootstrap", label: "Bootstrap" },
  { value: "mui", label: "MUI" },
  { value: "jest", label: "Jest" },
  { value: "junit", label: "JUnit" },
  { value: "postman", label: "Postman" },
  { value: "cucumber", label: "Cucumber" },
  { value: "ci_cd", label: "CI/CD" },
  { value: "jenkins", label: "Jenkins" },
  { value: "swagger", label: "Swagger" },
  { value: "microservices", label: "Microservices" },
  { value: "websockets", label: "WebSockets" },

  // Additional Skills
  { value: "nextjs", label: "Next.js" },
  { value: "vite", label: "Vite" },
  { value: "webpack", label: "Webpack" },
  { value: "babel", label: "Babel" },
  { value: "tailwindcss", label: "Tailwind CSS" },
  { value: "npm", label: "NPM" },
  { value: "yarn", label: "Yarn" },
  { value: "firebase", label: "Firebase" },
  { value: "supabase", label: "Supabase" },
  { value: "storybook", label: "Storybook" },
  { value: "sonarqube", label: "SonarQube" },
  { value: "puppeteer", label: "Puppeteer" },
  { value: "cypress", label: "Cypress" },
  { value: "eslint", label: "ESLint" },
  { value: "prettier", label: "Prettier" },
  { value: "nginx", label: "Nginx" },
  { value: "apache", label: "Apache" },
  { value: "elasticSearch", label: "Elasticsearch" },
  { value: "logstash", label: "Logstash" },
  { value: "kibana", label: "Kibana" },
  { value: "rabbitmq", label: "RabbitMQ" },
  { value: "kafka", label: "Kafka" },
  { value: "terraform", label: "Terraform" },
  { value: "ansible", label: "Ansible" },
  { value: "prometheus", label: "Prometheus" },
  { value: "grafana", label: "Grafana" },
  { value: "unity", label: "Unity" },
  { value: "blender", label: "Blender" },
  { value: "openai", label: "OpenAI API" }
];
