const options = [
    { value: "bachelor_cs", label: "Bachelor in Computer Science" },
    { value: "bachelor_it", label: "Bachelor in Information Technology" },
    { value: "bachelor_se", label: "Bachelor in Software Engineering" },
    { value: "bachelor_cyber", label: "Bachelor in Cybersecurity" },
    { value: "bachelor_ai", label: "Bachelor in Artificial Intelligence" },
    { value: "bachelor_ds", label: "Bachelor in Data Science" },
    { value: "master_cs", label: "Master in Computer Science" },
    { value: "master_it", label: "Master in Information Technology" },
    { value: "master_se", label: "Master in Software Engineering" },
    { value: "master_cyber", label: "Master in Cybersecurity" },
    { value: "master_ai", label: "Master in Artificial Intelligence" },
    { value: "master_ds", label: "Master in Data Science" },
    { value: "phd_cs", label: "PhD in Computer Science" },
    { value: "phd_it", label: "PhD in Information Technology" },
    { value: "phd_se", label: "PhD in Software Engineering" },
    { value: "phd_cyber", label: "PhD in Cybersecurity" },
    { value: "phd_ai", label: "PhD in Artificial Intelligence" },
    { value: "phd_ds", label: "PhD in Data Science" },
    { value: "diploma_cs", label: "Diploma in Computer Science" },
    { value: "diploma_it", label: "Diploma in Information Technology" },
    { value: "diploma_se", label: "Diploma in Software Engineering" },
    { value: "diploma_cyber", label: "Diploma in Cybersecurity" },
    { value: "diploma_ai", label: "Diploma in Artificial Intelligence" },
    { value: "diploma_ds", label: "Diploma in Data Science" },
    { value: "certificate_cs", label: "Certificate in Computer Science" },
    { value: "certificate_it", label: "Certificate in Information Technology" },
    { value: "certificate_se", label: "Certificate in Software Engineering" },
    { value: "certificate_cyber", label: "Certificate in Cybersecurity" },
    { value: "certificate_ai", label: "Certificate in Artificial Intelligence" },
    { value: "certificate_ds", label: "Certificate in Data Science" },
    { value: "associate_cs", label: "Associate Degree in Computer Science" },
    { value: "associate_it", label: "Associate Degree in Information Technology" },
    { value: "associate_se", label: "Associate Degree in Software Engineering" },
    { value: "associate_cyber", label: "Associate Degree in Cybersecurity" },
    { value: "associate_ai", label: "Associate Degree in Artificial Intelligence" },
    { value: "associate_ds", label: "Associate Degree in Data Science" },
    { value: "doctorate_cs", label: "Doctorate in Computer Science" },
    { value: "doctorate_it", label: "Doctorate in Information Technology" },
    { value: "doctorate_se", label: "Doctorate in Software Engineering" },
    { value: "doctorate_cyber", label: "Doctorate in Cybersecurity" },
    { value: "doctorate_ai", label: "Doctorate in Artificial Intelligence" },
    { value: "doctorate_ds", label: "Doctorate in Data Science" },
    { value: "postdoc_cs", label: "Postdoctoral in Computer Science" },
    { value: "postdoc_it", label: "Postdoctoral in Information Technology" },
    { value: "postdoc_se", label: "Postdoctoral in Software Engineering" },
    { value: "postdoc_cyber", label: "Postdoctoral in Cybersecurity" },
    { value: "postdoc_ai", label: "Postdoctoral in Artificial Intelligence" },
    { value: "postdoc_ds", label: "Postdoctoral in Data Science" },
    { value: "highschool", label: "High School" },
    { value: "other", label: "Other" }
  ]


  export default options